

$(document).ready(function(){
	

	setInterval(function(){$('#page_color').css('background', '#3BA'),
				setInterval(function(){$('#page_color').css('background', '#4AB')}, 
					$('#color_css').append($('<span style="color: #4AB; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#59B')}, 
					$('#color_css').append($('<span style="color: #59B; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#66B')}, 
					$('#color_css').append($('<span style="color: #66B; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#83A')}, 
					$('#color_css').append($('<span style="color: #83A; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#63B')}, 
					$('#color_css').append($('<span style="color: #63B; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#A3A')}, 
					$('#color_css').append($('<span style="color: #A3A; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#A59')}, 
					$('#color_css').append($('<span style="color: #A59; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#A77')}, 
					$('#color_css').append($('<span style="color: #A77; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'orange')}, 
					$('#color_css').append($('<span style="color: orange; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'blue')}, 
					$('#color_css').append($('<span style="color: blue; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'lime')}, 
					$('#color_css').append($('<span style="color: lime; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'red')}, 
					$('#color_css').append($('<span style="color: red; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'green')}, 
					$('#color_css').append($('<span style="color: green; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'purple')}, 
					$('#color_css').append($('<span style="color: purple; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'brown')}, 
					$('#color_css').append($('<span style="color: brown; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'yellow')}, 
					$('#color_css').append($('<span style="color: yellow; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'pink')}, 
					$('#color_css').append($('<span style="color: pink; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'silver')}, 
					$('#color_css').append($('<span style="color: silver; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'aqua')}, 
					$('#color_css').append($('<span style="color: aqua; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'tomato')}, 
					$('#color_css').append($('<span style="color: tomato; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'skyblue')}, 
					$('#color_css').append($('<span style="color: skyblue; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#66B')}, 
					$('#color_css').append($('<span style="color: #66B; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#83A')}, 
					$('#color_css').append($('<span style="color: #83A; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#63B')}, 
					$('#color_css').append($('<span style="color: #63B; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#A3A')}, 
					$('#color_css').append($('<span style="color: #A3A; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#A59')}, 
					$('#color_css').append($('<span style="color: #A59; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#A77')}, 
					$('#color_css').append($('<span style="color: #A77; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'orange')}, 
					$('#color_css').append($('<span style="color: orange; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'blue')}, 
					$('#color_css').append($('<span style="color: blue; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'lime')}, 
					$('#color_css').append($('<span style="color: lime; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'red')}, 
					$('#color_css').append($('<span style="color: red; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'green')}, 
					$('#color_css').append($('<span style="color: green; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'purple')}, 
					$('#color_css').append($('<span style="color: purple; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'brown')}, 
					$('#color_css').append($('<span style="color: brown; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'yellow')}, 
					$('#color_css').append($('<span style="color: yellow; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'pink')}, 
					$('#color_css').append($('<span style="color: pink; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'silver')}, 
					$('#color_css').append($('<span style="color: silver; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'aqua')}, 
					$('#color_css').append($('<span style="color: aqua; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#FFFFFF')}, 
					$('#color_css').append($('<span style="color: #FFFFFF; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#733626')}, 
					$('#color_css').append($('<span style="color: #733626; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#807F90')}, 
					$('#color_css').append($('<span style="color: #807F90; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#D1EC88')}, 
					$('#color_css').append($('<span style="color: #D1EC88; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#859B48')}, 
					$('#color_css').append($('<span style="color: #859B48; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#3C6459')}, 
					$('#color_css').append($('<span style="color: #3C6459; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#66B')}, 
					$('#color_css').append($('<span style="color: #66B; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#83A')}, 
					$('#color_css').append($('<span style="color: #83A; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#63B')}, 
					$('#color_css').append($('<span style="color: #63B; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#A3A')}, 
					$('#color_css').append($('<span style="color: #A3A; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#A59')}, 
					$('#color_css').append($('<span style="color: #A59; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#A77')}, 
					$('#color_css').append($('<span style="color: #A77; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'orange')}, 
					$('#color_css').append($('<span style="color: orange; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'blue')}, 
					$('#color_css').append($('<span style="color: blue; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'lime')}, 
					$('#color_css').append($('<span style="color: lime; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'red')}, 
					$('#color_css').append($('<span style="color: red; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'green')}, 
					$('#color_css').append($('<span style="color: green; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'purple')}, 
					$('#color_css').append($('<span style="color: purple; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'brown')}, 
					$('#color_css').append($('<span style="color: brown; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'yellow')}, 
					$('#color_css').append($('<span style="color: yellow; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'pink')}, 
					$('#color_css').append($('<span style="color: pink; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'silver')}, 
					$('#color_css').append($('<span style="color: silver; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', 'aqua')}, 
					$('#color_css').append($('<span style="color: aqua; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#FFFFFF')}, 
					$('#color_css').append($('<span style="color: #FFFFFF; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#733626')}, 
					$('#color_css').append($('<span style="color: #733626; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#807F90')}, 
					$('#color_css').append($('<span style="color: #807F90; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#D1EC88')}, 
					$('#color_css').append($('<span style="color: #D1EC88; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#859B48')}, 
					$('#color_css').append($('<span style="color: #859B48; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#3C6459')}, 
					$('#color_css').append($('<span style="color: #3C6459; text-align: center;"></span>'))),
				setInterval(function(){$('#page_color').css('background', '#995')}, 
					$('#color_css').append($('<span style="color: #995; text-align: center;"></span>')))
	}, 2000);
	

	//var tempsreel = setInterval(horloge, 1000);

	/*setInterval(function(){$('#page_color').css('background', '#3BA'),
				setInterval(function(){$('#page_color').css('background', '#4AB')}, 
					$('#color_css').append($('<span style="color: #4AB; text-align: center;"> 1 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#59B')}, 
					$('#color_css').append($('<span style="color: #59B; text-align: center;"> 2 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#66B')}, 
					$('#color_css').append($('<span style="color: #66B; text-align: center;"> 3 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#83A')}, 
					$('#color_css').append($('<span style="color: #83A; text-align: center;"> This The Color Number 4 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#63B')}, 
					$('#color_css').append($('<span style="color: #63B; text-align: center;"> This The Color Number 5 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#A3A')}, 
					$('#color_css').append($('<span style="color: #A3A; text-align: center;"> This The Color Number 6 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#A59')}, 
					$('#color_css').append($('<span style="color: #A59; text-align: center;"> This The Color Number 7 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#A77')}, 
					$('#color_css').append($('<span style="color: #A77; text-align: center;"> This The Color Number 8 . </span>'))),//
				setInterval(function(){$('#page_color').css('background', 'orange')}, 
					$('#color_css').append($('<span style="color: orange; text-align: center;"> This The Color Number 9 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'blue')}, 
					$('#color_css').append($('<span style="color: blue; text-align: center;"> This The Color Number 10 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'lime')}, 
					$('#color_css').append($('<span style="color: lime; text-align: center;"> This The Color Number 11 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'red')}, 
					$('#color_css').append($('<span style="color: red; text-align: center;"> This The Color Number 12 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'green')}, 
					$('#color_css').append($('<span style="color: green; text-align: center;"> This The Color Number 13 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'purple')}, 
					$('#color_css').append($('<span style="color: purple; text-align: center;"> This The Color Number 14 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'brown')}, 
					$('#color_css').append($('<span style="color: brown; text-align: center;"> This The Color Number 15 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'yellow')}, 
					$('#color_css').append($('<span style="color: yellow; text-align: center;"> This The Color Number 16 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'pink')}, 
					$('#color_css').append($('<span style="color: pink; text-align: center;"> This The Color Number 17 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'silver')}, 
					$('#color_css').append($('<span style="color: silver; text-align: center;"> This The Color Number 18 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'aqua')}, 
					$('#color_css').append($('<span style="color: aqua; text-align: center;"> This The Color Number 19 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'tomato')}, 
					$('#color_css').append($('<span style="color: tomato; text-align: center;"> This The Color Number 20 . </span>'))),
				setInterval(function(){$('#page_color').css('background', 'skyblue')}, 
					$('#color_css').append($('<span style="color: skyblue; text-align: center;"> This The Color Number 21 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#FFFFFF')}, 
					$('#color_css').append($('<span style="color: #FFFFFF; text-align: center;"> This The Color Number 22 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#733626')}, 
					$('#color_css').append($('<span style="color: #733626; text-align: center;"> This The Color Number 23 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#807F90')}, 
					$('#color_css').append($('<span style="color: #807F90; text-align: center;"> This The Color Number 24 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#D1EC88')}, 
					$('#color_css').append($('<span style="color: #D1EC88; text-align: center;"> This The Color Number 25 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#859B48')}, 
					$('#color_css').append($('<span style="color: #859B48; text-align: center;"> This The Color Number 26 . </span>'))),
				setInterval(function(){$('#page_color').css('background', '#3C6459')}, 
					$('#color_css').append($('<span style="color: #3C6459; text-align: center;"> This The Color Number 27 . </span>'))),//
				setInterval(function(){$('#page_color').css('background', '#995')}, 
					$('#color_css').append($('<span style="color: #995; text-align: center;"> This The Color Number 28 . </span>')))
	}, 2000);*/

	//couleur();10
});

/*function couleur(){
	setTimeout(function(){$('body').css('background', '#3BA')}, 200);
	setTimeout(function(){$('body').css('background', '#4AB')}, 400);
	setTimeout(function(){$('body').css('background', '#59B')}, 600);
	setTimeout(function(){$('body').css('background', '#66B')}, 800);
	setTimeout(function(){$('body').css('background', '#63B')}, 1000);
	setTimeout(function(){$('body').css('background', '#83A')}, 1200);
	setTimeout(function(){$('body').css('background', '#A3A')}, 1400);
	setTimeout(function(){$('body').css('background', '#A59')}, 1600);
	setTimeout(function(){$('body').css('background', '#A77')}, 1800);
	setTimeout(function(){$('body').css('background', '#995')}, 2000);
}*/